/**
 * NOTE: This class is auto generated by the swagger code generator program (unset).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.api.dse.alerts.poc.controller;

import com.api.dse.alerts.poc.model.AlertObject;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-12-18T17:07:25.307+05:30")

@Api(value = "customerreferencedatamanagement", description = "the customerreferencedatamanagement API")
public interface CustomerreferencedatamanagementApi {

    @ApiOperation(value = "Retrieve Customer Alerts", notes = "Retrieve Customer Alerts", response = AlertObject.class, tags={ "Alerts", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "An array of alert type objects", response = AlertObject.class) })
    
    @RequestMapping(value = "/customerreferencedatamanagement/customermanager/customer/{customerid}/alerts",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<AlertObject> alerts(@ApiParam(value = "ID of customer for which to return alerts",required=true ) @PathVariable("customerid") Long customerid);

}
